version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: imobiliaria
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      ports: "3306:3306"
      volumes: mysql_data:/var/lib/mysql
      networks: imobiliaria_network

volumes:
  mysql_data:

networks:
  imobiliaria_network:
    driver: bridge